### ISSUE TITLE
Module not found: Can't resolve fs and path

### ISSUE THREAD

**Issue by VILLAN3LL3** [scottcorgan/file-exists#13]
Hi, I installed the file-exists package in my Angular 7 project. 
Currently I'm using it like this in an angular component:

```
import * as fileExists from 'file-exists';
[...]
  private getMarkerIconPath(tenantId: string): string {
    let faviconPath = `assets/themes/${tenantId.toLocaleUpperCase()}/favicon.png`;
    if (!fileExists.sync(faviconPath)) {
      faviconPath = 'assets/themes/default/favicon.png';
    }
    return faviconPath;
  }
```

When I try to build the project with `ng build` it leads to the following errors:

> ERROR in ./node_modules/file-exists/index.js
> Module not found: Error: Can't resolve 'fs' in '##projectName##\node_modules\file-exists'
> ERROR in ./node_modules/file-exists/index.js
> Module not found: Error: Can't resolve 'path' in '##projectName##\node_modules\file-exists'

It refers to the following line in your index.js:

```
const fs = require('fs')
const path = require('path')
```

Thanks in advance for helpin' me out.

**Comment by gswalden** [comment]
Angular does not support the fs module, see this comment: https://github.com/angular/angular-cli/issues/8272#issuecomment-341428996

This module is mainly written for use on Node.js backends.
