### ISSUE TITLE
How is file-exists supposed to work with require?

### ISSUE THREAD

**Issue by thasmo** [scottcorgan/file-exists#4]
When running `file-exists` within a required file, it's not compatible with how `require` builds the path to a file. Is this intended?

**index.js**

``` js
require('./subdir/run.js');
```

**subdir/run.js**

``` js
var fileExists = require('file-exists');
var path = './inc.js';

if(fileExists(path)) {
    require(path);
}
```

Running `node index.js` fails for `if(exists(path))` because `require` inside `subdir/run.js` resolves the `cwd` to `subdir/`, but `file-exists` seems to use the root where `index.js` is stored.

To get this going it's needed to use `fileExists(path, {root: __dirname})`.

Is this intended and what's the _normal_ way to use it in combination with `require`?

**Comment by gswalden** [comment]
This library is essentially syntactic sugar for the [fs](https://nodejs.org/api/fs.html) module, whose docs state:

> The relative path to a filename can be used. Remember, however, that this path will be relative to process.cwd().

In order to use the same variable for `fileExists()` and `require()`, an absolute path is foolproof.

**subdir/run.js**

``` js
var fileExists = require('file-exists');
var path = __dirname + '/inc.js';

if(fileExists(path)) {
    require(path);
}
```

**Comment by thasmo** [comment]
Thanks for clarification!
