### ISSUE TITLE
Can we use this npm for typescript.

### ISSUE THREAD

**Issue by MounicaChette** [scottcorgan/file-exists#6]
I am unable to use this npm package in typescript. We have angular2 app written in typescript. I am unable to import any thing from file-Exists and there are no ts files in this npm.

**Comment by scottcorgan** [comment]
I don't personally use Typescript, but I do accept PRs for a type definition file.

How are you using this on the client? It was made to be a Node.js only package.

**Comment by scottcorgan** [comment]
Going to close and leave the conversation open.
